baseURL = "https://organization.supply/"
languageCode = "en-us"
title = "Organization Supply"
themesDir = "themes"
theme = "organization-supply"


[params]
  # In most cases you will only want to use either one of these. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = "UA-153944999-1"
  google_tag_manager_id = ""

  [params.homepage_meta_tags]
    meta_description = "Organization.supply is a simple inventory management app."
    meta_og_title = "Organization.supply"
    meta_og_type = "website"
    meta_og_url = "https://organization.supply"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-serif-theme/master/images/tn.png"
    meta_og_description = "Looking for a simple inventory management app, that skips on al the options, but focuses on simplicity? This is the one!"
    
[menu]
  [[menu.main]]
    identifier = "Home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "Features"
    name = "Features"
    url = "/features/"
    weight = 10
  [[menu.main]]
    identifier = "Pricing"
    name = "Pricing"
    url = "/pricing/"
    weight = 20
  [[menu.main]]
    identifier = "Blog"
    name = "Blog"
    url = "/posts/"
    weight = 20
  [[menu.main]]
    identifier = "About"
    name = "About"
    url = "/about/"
    weight = 21
  [[menu.main]]
    identifier = "Github"
    name = "Github"
    url = "https://github.com/jplattel/organization.supply"
    weight = 21


  [[menu.footer]]
    identifier = "API"
    name = "API"
    url = "/api/"
    weight = 20

  [[menu.footer]]
    identifier = "Github"
    name = "Github"
    url = "https://github.com/jplattel/organization.supply"
    weight = 20

  [[menu.footer]]
    identifier = "Login"
    name = "App"
    url = "https://app.organization.supply"
    weight = 20