baseURL = "https://organization.supply/"
languageCode = "en-us"
title = "Organization Supply"
themesDir = "themes"
theme = "hugo-serif-theme"

[menu]
  [[menu.main]]
    identifier = "Home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "Features"
    name = "Features"
    url = "/features/"
    weight = 10
  [[menu.main]]
    identifier = "Pricing"
    name = "Pricing"
    url = "/pricing/"
    weight = 20
  [[menu.main]]
    identifier = "Blog"
    name = "Blog"
    url = "/posts/"
    weight = 20
  [[menu.main]]
    identifier = "About"
    name = "About"
    url = "/about/"
    weight = 21
  [[menu.main]]
    identifier = "Github"
    name = "Github"
    url = "https://github.com/jplattel/organization.supply"
    weight = 21

  [[menu.footer]]
    identifier = "Github"
    name = "Github"
    url = "https://github.com/jplattel/organization.supply"
    weight = 20