baseURL = "https://organization.supply/"
languageCode = "en-us"
title = "Organization Supply"
themesDir = "themes"
theme = "ananke"

[params]
body_classes = "avenir bg-near-white"
github = "https://github.com/jplattel/inventory"

[menu]
  [[menu.main]]
    identifier = "Home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "Features"
    name = "Features"
    url = "/features/"
    weight = 10
  [[menu.main]]
    identifier = "Pricing"
    name = "Pricing"
    url = "/pricing/"
    weight = 20