repos:
- repo: local
  hooks:
  - id: isort
    name: isort
    stages: [commit]
    language: system
    entry: isort -rc .
    types: [python]

  - id: black
    name: black
    stages: [commit]
    language: system
    entry: black .
    types: [python]

  - id: pytest-cov
    name: pytest
    stages: [push]
    language: system
    entry: pytest
    types: [python]
    pass_filenames: false

  - id: coveralls
    name: coveralls
    stages: [push]
    language: system
    entry: coveralls
    types: [python]
    pass_filenames: false
