version: 2
jobs:
  test:
    # branches:
    #   only:
    #     - master
    #     - develop
    environment:
      DEBUG: "True"
      SENTRY_DSN: ""
      SENDGRID_API_KEY: ""
      DJANGO_STATIC_ROOT: ""
      DJANGO_MEDIA_ROOT: ""
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout

      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - run:
          name: "Install dependencies"
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            mkdir test-reports
            pytest --cov . --junitxml=test-reports/junit.xml
            coveralls

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports

  # deploy:
  #   docker:
  #     - image: circleci/python:3.6
  #   steps:
  #     - run:
  #         name: Deploy
  #         command: |
  #           echo "Hello deploy!"

workflows:
  version: 2
  test:
    jobs:
      - test
      # - hold: # Deploy requires approval
      #     type: approval 
      # - deploy:
      #     requires:
      #       - hold