openapi: 3.0.2
info:
  title: Organization.supply REST API
  version: ''
  description: Documentation for the REST API for Organization.supply
paths:
  /{organization}/api/products:
    get:
      operationId: listProducts
      parameters:
      - name: organization
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    id:
                      type: string
                      format: uuid
                      readOnly: true
                    name:
                      type: string
                      maxLength: 200
                    desc:
                      type: string
                    image:
                      type: string
                      readOnly: true
                    price_cost:
                      type: number
                    price_sale:
                      type: number
                    tags:
                      type: array
                      items:
                        type: string
                      readOnly: true
                  required:
                  - name
          description: ''
    post:
      operationId: CreateProduct
      parameters:
      - name: organization
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                  maxLength: 200
                desc:
                  type: string
                price_cost:
                  type: number
                price_sale:
                  type: number
              required:
              - name
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: string
                    format: uuid
                    readOnly: true
                  name:
                    type: string
                    maxLength: 200
                  desc:
                    type: string
                  image:
                    type: string
                    readOnly: true
                  price_cost:
                    type: number
                  price_sale:
                    type: number
                  tags:
                    type: array
                    items:
                      type: string
                    readOnly: true
                required:
                - name
          description: ''
  /{organization}/api/products/{id}:
    get:
      operationId: RetrieveProduct
      parameters:
      - name: organization
        in: path
        required: true
        description: ''
        schema:
          type: string
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: string
                    format: uuid
                    readOnly: true
                  name:
                    type: string
                    maxLength: 200
                  desc:
                    type: string
                  image:
                    type: string
                    readOnly: true
                  price_cost:
                    type: number
                  price_sale:
                    type: number
                  tags:
                    type: array
                    items:
                      type: string
                    readOnly: true
                required:
                - name
          description: ''
    put:
      operationId: UpdateProduct
      parameters:
      - name: organization
        in: path
        required: true
        description: ''
        schema:
          type: string
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                  maxLength: 200
                desc:
                  type: string
                price_cost:
                  type: number
                price_sale:
                  type: number
              required:
              - name
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: string
                    format: uuid
                    readOnly: true
                  name:
                    type: string
                    maxLength: 200
                  desc:
                    type: string
                  image:
                    type: string
                    readOnly: true
                  price_cost:
                    type: number
                  price_sale:
                    type: number
                  tags:
                    type: array
                    items:
                      type: string
                    readOnly: true
                required:
                - name
          description: ''
    patch:
      operationId: PartialUpdateProduct
      parameters:
      - name: organization
        in: path
        required: true
        description: ''
        schema:
          type: string
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                  maxLength: 200
                desc:
                  type: string
                price_cost:
                  type: number
                price_sale:
                  type: number
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: string
                    format: uuid
                    readOnly: true
                  name:
                    type: string
                    maxLength: 200
                  desc:
                    type: string
                  image:
                    type: string
                    readOnly: true
                  price_cost:
                    type: number
                  price_sale:
                    type: number
                  tags:
                    type: array
                    items:
                      type: string
                    readOnly: true
                required:
                - name
          description: ''
    delete:
      operationId: DestroyProduct
      parameters:
      - name: organization
        in: path
        required: true
        description: ''
        schema:
          type: string
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '204':
          description: ''
  /{organization}/api/locations:
    get:
      operationId: listLocations
      parameters:
      - name: organization
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    id:
                      type: string
                      format: uuid
                      readOnly: true
                    name:
                      type: string
                      maxLength: 200
                    image:
                      type: string
                      readOnly: true
                    desc:
                      type: string
                    size:
                      type: number
                    tags:
                      type: array
                      items:
                        type: string
                      readOnly: true
                  required:
                  - name
          description: ''
    post:
      operationId: CreateLocation
      parameters:
      - name: organization
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                  maxLength: 200
                desc:
                  type: string
                size:
                  type: number
              required:
              - name
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: string
                    format: uuid
                    readOnly: true
                  name:
                    type: string
                    maxLength: 200
                  image:
                    type: string
                    readOnly: true
                  desc:
                    type: string
                  size:
                    type: number
                  tags:
                    type: array
                    items:
                      type: string
                    readOnly: true
                required:
                - name
          description: ''
  /{organization}/api/locations/{id}:
    get:
      operationId: RetrieveLocation
      parameters:
      - name: organization
        in: path
        required: true
        description: ''
        schema:
          type: string
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: string
                    format: uuid
                    readOnly: true
                  name:
                    type: string
                    maxLength: 200
                  image:
                    type: string
                    readOnly: true
                  desc:
                    type: string
                  size:
                    type: number
                  tags:
                    type: array
                    items:
                      type: string
                    readOnly: true
                required:
                - name
          description: ''
    put:
      operationId: UpdateLocation
      parameters:
      - name: organization
        in: path
        required: true
        description: ''
        schema:
          type: string
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                  maxLength: 200
                desc:
                  type: string
                size:
                  type: number
              required:
              - name
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: string
                    format: uuid
                    readOnly: true
                  name:
                    type: string
                    maxLength: 200
                  image:
                    type: string
                    readOnly: true
                  desc:
                    type: string
                  size:
                    type: number
                  tags:
                    type: array
                    items:
                      type: string
                    readOnly: true
                required:
                - name
          description: ''
    patch:
      operationId: PartialUpdateLocation
      parameters:
      - name: organization
        in: path
        required: true
        description: ''
        schema:
          type: string
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                  maxLength: 200
                desc:
                  type: string
                size:
                  type: number
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: string
                    format: uuid
                    readOnly: true
                  name:
                    type: string
                    maxLength: 200
                  image:
                    type: string
                    readOnly: true
                  desc:
                    type: string
                  size:
                    type: number
                  tags:
                    type: array
                    items:
                      type: string
                    readOnly: true
                required:
                - name
          description: ''
    delete:
      operationId: DestroyLocation
      parameters:
      - name: organization
        in: path
        required: true
        description: ''
        schema:
          type: string
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '204':
          description: ''
  /{organization}/api/inventory:
    get:
      operationId: listInventorys
      parameters:
      - name: organization
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    id:
                      type: string
                      format: uuid
                      readOnly: true
                    product:
                      type: string
                    location:
                      type: string
                    amount:
                      type: number
                  required:
                  - product
                  - location
          description: ''
  /{organization}/api/mutations:
    get:
      operationId: listMutations
      parameters:
      - name: organization
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    id:
                      type: string
                      format: uuid
                      readOnly: true
                    amount:
                      type: number
                    product:
                      type: string
                    location:
                      type: string
                    desc:
                      type: string
                    operation:
                      enum:
                      - add
                      - remove
                      - reserved
                  required:
                  - amount
                  - product
                  - location
          description: ''
    post:
      operationId: CreateMutation
      parameters:
      - name: organization
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                amount:
                  type: number
                product:
                  type: string
                location:
                  type: string
                desc:
                  type: string
                operation:
                  enum:
                  - add
                  - remove
                  - reserved
              required:
              - amount
              - product
              - location
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: string
                    format: uuid
                    readOnly: true
                  amount:
                    type: number
                  product:
                    type: string
                  location:
                    type: string
                  desc:
                    type: string
                  operation:
                    enum:
                    - add
                    - remove
                    - reserved
                required:
                - amount
                - product
                - location
          description: ''
  /{organization}/api/me:
    get:
      operationId: RetrieveUser
      parameters:
      - name: organization
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: string
                    format: uuid
                    readOnly: true
                  email:
                    type: string
                    format: email
                    maxLength: 254
                  name:
                    type: string
                    maxLength: 255
                required:
                - email
          description: ''
  /{organization}/api/notifications:
    get:
      operationId: listNotifications
      parameters:
      - name: organization
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    id:
                      type: integer
                      readOnly: true
                    timestamp:
                      type: string
                      format: date-time
                    description:
                      type: string
                      nullable: true
                    verb:
                      type: string
                      maxLength: 255
                  required:
                  - verb
          description: ''
